services:
  - type: web
    name: shl-assessment-recommender-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
